package protocol

// ConnectorCapabilityRegistry describes source/tool adapter behavior needed for
// source planning, review gates, package manifests, and dashboard warnings.
type ConnectorCapabilityRegistry struct {
	SchemaVersion string                `json:"schemaVersion"`
	Connectors    []ConnectorCapability `json:"connectors"`
}

type ConnectorCapability struct {
	ID                        string   `json:"id"`
	Label                     string   `json:"label"`
	Kind                      string   `json:"kind"`
	SupportedEntities         []string `json:"supportedEntities"`
	RateLimitPolicy           string   `json:"rateLimitPolicy"`
	AuthNeeds                 string   `json:"authNeeds"`
	LiveSmokeStatus           string   `json:"liveSmokeStatus"`
	LicenseShareabilityPolicy string   `json:"licenseShareabilityPolicy"`
	Cacheability              string   `json:"cacheability"`
	ProvenanceFields          []string `json:"provenanceFields"`
}

func DefaultConnectorCapabilityRegistry() ConnectorCapabilityRegistry {
	return ConnectorCapabilityRegistry{SchemaVersion: "1", Connectors: []ConnectorCapability{
		{ID: "openalex", Label: "OpenAlex", Kind: "scholarly-source", SupportedEntities: []string{"works", "authors", "institutions", "concepts", "references", "citations"}, RateLimitPolicy: "public polite API; cursor/resume state required for multi-page imports", AuthNeeds: "none", LiveSmokeStatus: "covered by source-live-smoke", LicenseShareabilityPolicy: "open metadata; preserve source IDs and request provenance", Cacheability: "cache query responses with request parameters and cursor state", ProvenanceFields: []string{"source", "query", "filters", "cursor", "work_id", "raw_ref"}},
		{ID: "semantic-scholar", Label: "Semantic Scholar", Kind: "scholarly-source", SupportedEntities: []string{"papers", "authors", "references", "citations"}, RateLimitPolicy: "quota/rate limited; Retry-After honored by shared HTTP backoff", AuthNeeds: "optional RFORGE_SEMANTIC_SCHOLAR_API_KEY", LiveSmokeStatus: "covered by semantic-scholar-live-smoke", LicenseShareabilityPolicy: "API terms and field restrictions apply; cache only documented fields", Cacheability: "cache normalized metadata and graph refs with field list", ProvenanceFields: []string{"source", "query", "paper_id", "direction", "depth", "fields", "raw_ref"}},
		{ID: "crossref", Label: "Crossref", Kind: "scholarly-source", SupportedEntities: []string{"works", "doi", "references"}, RateLimitPolicy: "public polite API; request parameters must be recorded", AuthNeeds: "none", LiveSmokeStatus: "covered by source-live-smoke", LicenseShareabilityPolicy: "metadata terms vary by publisher; preserve DOI/source refs", Cacheability: "cache DOI/work lookups with request URL", ProvenanceFields: []string{"source", "query", "doi", "rows", "raw_ref"}},
		{ID: "arxiv", Label: "arXiv", Kind: "scholarly-source", SupportedEntities: []string{"preprints", "categories", "versions", "pdf", "source"}, RateLimitPolicy: "public API; polite pauses required for bulk workflows", AuthNeeds: "none", LiveSmokeStatus: "covered by source-live-smoke", LicenseShareabilityPolicy: "preprint metadata open; full-text/source license still captured per asset", Cacheability: "cache Atom responses and fetched asset checksums", ProvenanceFields: []string{"source", "query", "category", "arxiv_id", "version", "raw_ref"}},
		{ID: "pubmed", Label: "PubMed", Kind: "scholarly-source", SupportedEntities: []string{"articles", "pmid", "mesh", "biomedical metadata"}, RateLimitPolicy: "NCBI E-utilities policy; API key/email may raise limits", AuthNeeds: "optional NCBI API key/email", LiveSmokeStatus: "covered by biomedical-live-smoke", LicenseShareabilityPolicy: "metadata public; full text requires PMC/OA license checks", Cacheability: "cache query IDs and normalized metadata", ProvenanceFields: []string{"source", "query", "pmid", "retstart", "retmax", "raw_ref"}},
		{ID: "europepmc", Label: "Europe PMC", Kind: "scholarly-source", SupportedEntities: []string{"articles", "pmid", "pmcid", "full-text links", "license metadata"}, RateLimitPolicy: "public API; pagination/request params recorded", AuthNeeds: "none", LiveSmokeStatus: "covered by biomedical-live-smoke", LicenseShareabilityPolicy: "OA/full-text license fields must gate acquisition", Cacheability: "cache result pages and license metadata", ProvenanceFields: []string{"source", "query", "pmid", "pmcid", "page", "raw_ref"}},
		{ID: "nasa-ads", Label: "NASA ADS", Kind: "scholarly-source", SupportedEntities: []string{"bibcodes", "works", "authors", "references", "citations"}, RateLimitPolicy: "ADS API quota/rate limits; token usage must be recorded without secrets", AuthNeeds: "NASA ADS token required for live API", LiveSmokeStatus: "planned opt-in live smoke", LicenseShareabilityPolicy: "ADS terms apply; preserve bibcodes and requested fields", Cacheability: "cache normalized metadata and bibcode graph refs", ProvenanceFields: []string{"source", "query", "bibcode", "fields", "raw_ref"}},
		{ID: "doaj", Label: "DOAJ", Kind: "open-access-discovery", SupportedEntities: []string{"journals", "articles", "licenses", "oa candidates"}, RateLimitPolicy: "public API; attribution and request params recorded", AuthNeeds: "none", LiveSmokeStatus: "planned opt-in live smoke", LicenseShareabilityPolicy: "OA metadata is not automatic redistribution permission; record license", Cacheability: "cache metadata/license candidates", ProvenanceFields: []string{"source", "query", "doi", "license", "raw_ref"}},
		{ID: "core", Label: "CORE", Kind: "open-access-discovery", SupportedEntities: []string{"articles", "repositories", "full-text candidates", "licenses"}, RateLimitPolicy: "CORE API limits; key may be required", AuthNeeds: "CORE API key may be required", LiveSmokeStatus: "planned opt-in live smoke", LicenseShareabilityPolicy: "full-text links require explicit license/shareability review", Cacheability: "cache candidate metadata, not private payloads", ProvenanceFields: []string{"source", "query", "doi", "repository", "license", "raw_ref"}},
		{ID: "biorxiv", Label: "bioRxiv / medRxiv", Kind: "preprint-server", SupportedEntities: []string{"preprints", "doi", "category", "recent-listing"}, RateLimitPolicy: "public API; polite usage expected; no keyword search — lists by date range and filters locally", AuthNeeds: "none", LiveSmokeStatus: "planned opt-in live smoke", LicenseShareabilityPolicy: "preprint metadata open; full-text license captured per asset", Cacheability: "cache date-range listing responses", ProvenanceFields: []string{"source", "server", "interval", "query", "doi", "raw_ref"}},
		{ID: "zenodo", Label: "Zenodo", Kind: "scholarly-source", SupportedEntities: []string{"records", "datasets", "software", "preprints", "doi"}, RateLimitPolicy: "public API; no auth required for search", AuthNeeds: "none", LiveSmokeStatus: "planned opt-in live smoke", LicenseShareabilityPolicy: "license field must gate acquisition; open access flag is per-record", Cacheability: "cache query responses with size/sort params", ProvenanceFields: []string{"source", "query", "size", "sort", "doi", "raw_ref"}},
		{ID: "inspire-hep", Label: "INSPIRE HEP", Kind: "scholarly-source", SupportedEntities: []string{"literature", "authors", "doi", "arxiv-eprints", "publication-info"}, RateLimitPolicy: "public REST API; polite usage expected", AuthNeeds: "none", LiveSmokeStatus: "planned opt-in live smoke", LicenseShareabilityPolicy: "metadata open; full-text from arXiv where available", Cacheability: "cache query responses with size/sort params", ProvenanceFields: []string{"source", "query", "size", "inspire_id", "doi", "arxiv_id", "raw_ref"}},
		{ID: "dblp", Label: "DBLP", Kind: "scholarly-source", SupportedEntities: []string{"publications", "authors", "doi", "venue"}, RateLimitPolicy: "public API; polite usage; avoid bulk automated queries", AuthNeeds: "none", LiveSmokeStatus: "planned opt-in live smoke", LicenseShareabilityPolicy: "metadata open under ODC-By; preserve source attribution", Cacheability: "cache query responses with h/f params", ProvenanceFields: []string{"source", "query", "h", "f", "doi", "raw_ref"}},
		{ID: "clinicaltrials", Label: "ClinicalTrials.gov", Kind: "scholarly-source", SupportedEntities: []string{"studies", "nct-id", "sponsor", "status", "conditions"}, RateLimitPolicy: "public API v2; no auth required", AuthNeeds: "none", LiveSmokeStatus: "planned opt-in live smoke", LicenseShareabilityPolicy: "trial registration data is public; no full-text acquisition", Cacheability: "cache study listings with query.term and pageSize", ProvenanceFields: []string{"source", "query", "nct_id", "sponsor", "raw_ref"}},
		{ID: "osf", Label: "OSF Preprints", Kind: "preprint-server", SupportedEntities: []string{"preprints", "doi", "tags", "license"}, RateLimitPolicy: "public API; covers PsyArXiv, SocArXiv, EarthArXiv, and others", AuthNeeds: "none", LiveSmokeStatus: "planned opt-in live smoke", LicenseShareabilityPolicy: "license field per preprint; OA by default but verify before redistribution", Cacheability: "cache filter[title] and page[size] responses", ProvenanceFields: []string{"source", "query", "doi", "tags", "raw_ref"}},
		{ID: "opencitations", Label: "OpenCitations (COCI)", Kind: "citation-graph", SupportedEntities: []string{"citations", "references", "doi", "metadata"}, RateLimitPolicy: "public REST API; no auth required; polite usage expected", AuthNeeds: "none", LiveSmokeStatus: "planned opt-in live smoke", LicenseShareabilityPolicy: "citation data CC0; metadata from citing works carries original licenses", Cacheability: "cache citations/{doi} and metadata/{dois} responses", ProvenanceFields: []string{"source", "cited_doi", "citing_doi", "creation", "timespan", "raw_ref"}},
		{ID: "base", Label: "BASE (Bielefeld Academic Search Engine)", Kind: "scholarly-source", SupportedEntities: []string{"articles", "oai-records", "doi", "open-access"}, RateLimitPolicy: "public API; polite usage; attribution expected", AuthNeeds: "none", LiveSmokeStatus: "planned opt-in live smoke", LicenseShareabilityPolicy: "CC license field gates acquisition; OA inferred from dcrights", Cacheability: "cache PerformSearch responses with query/hits/offset", ProvenanceFields: []string{"source", "query", "hits", "offset", "oai_id", "doi", "raw_ref"}},
		{ID: "zbmath", Label: "zbMATH Open", Kind: "scholarly-source", SupportedEntities: []string{"articles", "doi", "zbl-id", "msc-codes"}, RateLimitPolicy: "public API since 2021; polite usage expected", AuthNeeds: "none", LiveSmokeStatus: "planned opt-in live smoke", LicenseShareabilityPolicy: "metadata open; preserve zbMATH ID and MSC codes", Cacheability: "cache document search responses with q and per_page", ProvenanceFields: []string{"source", "query", "per_page", "zbl_id", "doi", "msc_codes", "raw_ref"}},
		{ID: "figshare", Label: "figshare", Kind: "scholarly-source", SupportedEntities: []string{"datasets", "preprints", "software", "presentations", "doi"}, RateLimitPolicy: "public API; no auth required for read", AuthNeeds: "none", LiveSmokeStatus: "planned opt-in live smoke", LicenseShareabilityPolicy: "license field per item; OA from CC license URL; verify before redistribution", Cacheability: "cache article search responses with search_for and page_size", ProvenanceFields: []string{"source", "query", "page_size", "figshare_id", "doi", "defined_type", "raw_ref"}},
		{ID: "datacite", Label: "DataCite", Kind: "scholarly-source", SupportedEntities: []string{"datasets", "software", "doi", "research-data"}, RateLimitPolicy: "public REST API; no auth required", AuthNeeds: "none", LiveSmokeStatus: "planned opt-in live smoke", LicenseShareabilityPolicy: "rights field per record; OA if CC license URI present", Cacheability: "cache /dois query responses with query and page[size]", ProvenanceFields: []string{"source", "query", "page_size", "doi", "resource_type", "raw_ref"}},
		{ID: "lens", Label: "Lens.org", Kind: "scholarly-source", SupportedEntities: []string{"scholarly-works", "patents", "doi", "arxiv", "authors", "citations"}, RateLimitPolicy: "free academic API; JWT token required; rate limits apply per token", AuthNeeds: "RFORGE_LENS_TOKEN (JWT bearer token from lens.org)", LiveSmokeStatus: "planned opt-in live smoke", LicenseShareabilityPolicy: "metadata open under CC0 for scholarly data; patent data governed by Lens terms", Cacheability: "cache POST /scholarly/search responses with query body hash", ProvenanceFields: []string{"source", "query", "size", "lens_id", "doi", "arxiv_id", "raw_ref"}},
		{ID: "eric", Label: "ERIC", Kind: "scholarly-source", SupportedEntities: []string{"articles", "reports", "ed-number", "ej-number", "subjects"}, RateLimitPolicy: "public US Dept of Education API; no auth required", AuthNeeds: "none", LiveSmokeStatus: "covered by source-live-smoke", LicenseShareabilityPolicy: "government-produced metadata is public domain; full text varies by publisher", Cacheability: "cache search responses with query and rows params", ProvenanceFields: []string{"source", "query", "eric_id", "peerreviewed", "raw_ref"}},
		{ID: "hal", Label: "HAL (Hyper Articles en Ligne)", Kind: "scholarly-source", SupportedEntities: []string{"articles", "preprints", "doi", "hal-id", "open-access"}, RateLimitPolicy: "public SOLR API; no auth required; polite usage expected", AuthNeeds: "none", LiveSmokeStatus: "covered by source-live-smoke", LicenseShareabilityPolicy: "OA flag drives acquisition eligibility; verify license per record", Cacheability: "cache search responses with q and rows params", ProvenanceFields: []string{"source", "query", "hal_id", "doi", "raw_ref"}},
		{ID: "dimensions", Label: "Dimensions", Kind: "scholarly-source", SupportedEntities: []string{"publications", "grants", "patents", "doi", "open-access"}, RateLimitPolicy: "free academic API; JWT token required; rate limits apply per token", AuthNeeds: "RFORGE_DIMENSIONS_TOKEN (JWT from app.dimensions.ai)", LiveSmokeStatus: "planned opt-in live smoke", LicenseShareabilityPolicy: "metadata open; patent data governed by Dimensions terms", Cacheability: "cache POST DSL responses keyed by query hash", ProvenanceFields: []string{"source", "query", "dimensions_id", "doi", "raw_ref"}},
		{ID: "pubchem", Label: "PubChem", Kind: "chemistry-database", SupportedEntities: []string{"compounds", "cid", "molecular-formula", "inchikey", "smiles"}, RateLimitPolicy: "public NCBI API; rate limits apply for unauthenticated access; two-step query", AuthNeeds: "none", LiveSmokeStatus: "covered by source-live-smoke", LicenseShareabilityPolicy: "all PubChem data CC0; open for redistribution", Cacheability: "cache name→CID and CID→properties responses", ProvenanceFields: []string{"source", "query", "cid", "inchikey", "raw_ref"}},
		{ID: "unpaywall", Label: "Unpaywall", Kind: "oa-lookup", SupportedEntities: []string{"doi", "oa status", "best oa location", "pdf url", "license"}, RateLimitPolicy: "email/contact expected for polite usage", AuthNeeds: "RFORGE_UNPAYWALL_EMAIL for live smoke", LiveSmokeStatus: "covered by source-live-smoke when email configured", LicenseShareabilityPolicy: "license and host type gate PDF acquisition", Cacheability: "cache DOI lookups and OA location metadata", ProvenanceFields: []string{"source", "doi", "oa_status", "license", "raw_ref"}},
		{ID: "zotero", Label: "Zotero", Kind: "reference-manager", SupportedEntities: []string{"items", "collections", "tags", "notes", "annotations", "attachments"}, RateLimitPolicy: "local export/import; no network by default", AuthNeeds: "local export file", LiveSmokeStatus: "not applicable; fixture round-trip tests", LicenseShareabilityPolicy: "notes/attachments/local paths require privacy/license review", Cacheability: "store imported normalized records and source metadata", ProvenanceFields: []string{"source", "format", "item_id", "collection", "attachment_redaction"}},
		{ID: "jabref", Label: "JabRef", Kind: "reference-manager", SupportedEntities: []string{"bibtex", "biblatex", "groups", "citation keys", "linked files"}, RateLimitPolicy: "local import/export; no network by default", AuthNeeds: "local BibTeX/BibLaTeX file", LiveSmokeStatus: "not applicable; fixture round-trip tests", LicenseShareabilityPolicy: "linked-file fields may expose private paths", Cacheability: "store normalized records and cleanup diff provenance", ProvenanceFields: []string{"source", "format", "citation_key", "group", "linked_file_redaction"}},
		{ID: "local", Label: "Local files", Kind: "local-import", SupportedEntities: []string{"pdf", "xml", "jats", "html", "text", "notes"}, RateLimitPolicy: "local filesystem only", AuthNeeds: "local path access", LiveSmokeStatus: "not applicable; local fixtures", LicenseShareabilityPolicy: "local files private until acquisition/shareability approved", Cacheability: "record checksums and local-only/redaction status", ProvenanceFields: []string{"source", "path", "checksum", "mime_type", "shareability"}},
	}}
}

func (r ConnectorCapabilityRegistry) ByID(id string) (ConnectorCapability, bool) {
	for _, capability := range r.Connectors {
		if capability.ID == id {
			return capability, true
		}
	}
	return ConnectorCapability{}, false
}
